name: 15-mins-cron
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url '${{ secrets.CORN_URL }}' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'